### PR TITLE
Add OpenGL device (dri)

### PR DESCRIPTION
**Pull request by foldynl**
Sometimes QT dialogs are rendered with a black border. Adding device=dri fixes this issue.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
> Sometimes QT dialogs are rendered with a black border. Adding device=dri fixes this issue.

Are you really sure? Because the `--device=all` permission already includes `--device=dri`. Also, I have seen no black borders. What desktop environment do you use?

**Comment by foldynl** [comment]
I'm sorry my mistake. It was weird to me. I made a mistake while testing (you know...flatpak newbie). 

I have test instances in vmware workstation because there are many platforms for QLog testing. I performed this test on Ubuntu 22.04 (vmware has exported OpenGL via the vmware driver) and can confirm that `dri` has ***NO*** effect. 

The problem of the black dialog "circle" seems to be an issue somewhere in QT. Especially in the parts that, I believe, are modified for flatpak (file selection dialogs). See example below. The same flatpak package under XOrg and Wayland

XOrg
XOrg

Wayland
wayland

This issue occurs only in case of System dialogs and Wayland. Qlog's dialogs are not impacted. I tried other qt applications and the result is the same.

Another problem is "(None)" in the file filter. I can't explain it at all, because it only appears when QLog is installed from flatpak - there is the same code for flatpak and binary.

**Comment by foldynl** [comment]
> Another problem is "(None)" in the file filter. I can't explain it at all, because it only appears when QLog is installed from flatpak - there is the same code for flatpak and binary.

I found a fix for it.

only what is shown in the pictures remains - if there is any solution for it

**Comment by AsciiWolf** [comment]
I am not able to reproduce the issue from your screenshot on my Fedora 39 system running Wayland. I suspect that the problem may be Ubuntu-related since they tend to have really bad Flatpak support (basically none - the "flatpak" package is just synced from Debian without any testing and Canonical does not care about Flatpak at all).

**Comment by bbhtt** [comment]
You can remove the flathub-json cleanup now.

**Comment by foldynl** [comment]
so I finally found the cause of the black border. It seems to be a VMware HW 3D acceleration issue. If I turn it off, the edge disappears for Wayland as well.

So consider my PR useless.

**Pull request closed without merging**
